create database naturale;

create table usuario(
    id_usuario INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_usuario varchar(200) not null,
    telefone_usuario varchar(200) not null UNIQUE,
    cpf_usuario varchar(200) not null UNIQUE,
    email_usuario varchar(200) not null UNIQUE,
    senha_usuario varchar(200) not null
);

--Titulo/texto/ingredientes/tempo -> Fazem referencia à receita/comida!
--Status -> colocar como default 1(ativo)
create table post(
    id_post INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario int not null,

    titulo_post varchar(200) not null,
    texto_post varchar(400) not null,
    ingredientes_post varchar(400) not null,
    tempo_post varchar(100) not null,
    qtd_curtidas int not null,
    
    status_post BOOLEAN not null,
    FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario)
);

--Tabela para registrar os likes(controle para curtir/descurtir)
create table likes(
    id_likes INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario int not null,
    id_post int not null,

    FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario),
    FOREIGN KEY (id_post) REFERENCES post(id_post)
);

--Enabling on cascade process do delete foreign keys
ALTER TABLE post
DROP CONSTRAINT post_id_usuario_fkey,  -- Drop the existing foreign key constraint
ADD CONSTRAINT post_id_usuario_fkey FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario) ON DELETE CASCADE;

ALTER TABLE likes
DROP CONSTRAINT likes_id_usuario_fkey, 
ADD CONSTRAINT likes_id_usuario_fkey FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario) ON DELETE CASCADE;

ALTER TABLE likes
DROP CONSTRAINT likes_id_post_fkey,
ADD CONSTRAINT likes_id_post_fkey FOREIGN KEY (id_post) REFERENCES post(id_post) ON DELETE CASCADE;


insert into usuario(nome_usuario, telefone_usuario, cpf_usuario, email_usuario, senha_usuario) values('Matheus', '988257303', '53826433858', 'math@gmail.com', '123456');
insert into usuario(nome_usuario, telefone_usuario, cpf_usuario, email_usuario, senha_usuario) values('Pedro', '11988257303', '123456789', 'pedro@gmail.com', '123456789');

insert into post(id_usuario, titulo_post, texto_post, ingredientes_post, tempo_post, qtd_curtidas, status_post) values(1, 'Strogonoff de Frango', 'Passo a passo: Lorem ipsum dolor sit amet', '1kg de Frango, 450g de arroz, 2 alhos, 2 colheres de sopa de manteiga...', '45 mins', 0,true);
insert into post(id_usuario, titulo_post, texto_post, ingredientes_post, tempo_post, qtd_curtidas, status_post) values(1, 'Lasanha de Carne', 'Passo a passo: Lorem ipsum dolor sit amet', '1kg de Carne, 450g de arroz, 2 alhos, 2 colheres de sopa de manteiga...', '1h', 0,true);
insert into post(id_usuario, titulo_post, texto_post, ingredientes_post, tempo_post, qtd_curtidas, status_post) values(1, 'Stronoff de Carne', 'Passo a passo: Lorem ipsum dolor sit amet', '1kg de Carne, 450g de arroz, 2 alhos, 2 colheres de sopa de manteiga...', '1h', 0,true);

insert into post(id_usuario, titulo_post, texto_post, ingredientes_post, tempo_post, qtd_curtidas, status_post) values(6, 'Feijoada', 'Passo a passo: Lorem ipsum dolor sit amet', '1kg de Carne de porco, 500g de arroz, 500g de couve...', '2h', 0,true);