create database naturale;

create table users(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(200) not null,
    username varchar(200) null,
    phone varchar(200) null UNIQUE,
    cpf varchar(200) null UNIQUE,
    email varchar(200) not null UNIQUE,
    password varchar(200) null,
    avatar varchar(400) null,
    --Aqui ele pode ser ou ADMIN ou USER, então varchar(5)
    type varchar(5) not null
);

--Titulo/texto/ingredientes/tempo -> Fazem referencia à receita/comida!
--Status -> colocar como default 1 (ativo)
create table post(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int not null,

    title varchar(200) not null,
    text varchar(400) not null,
    ingredients varchar(400) not null,
    image varchar(400) not null,
    time varchar(100) not null,
    likes_count int not null,
    
    status BOOLEAN not null,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

--Tabela para registrar os likes (controle para curtir/descurtir)
create table likes(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int not null,
    post_id int not null,

    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (post_id) REFERENCES post(id)
);

create table favorites(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int not null,
    post_id int not null,

    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (post_id) REFERENCES post(id)
);

create table comments(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int not null,
    post_id int not null,
    parent_comment_id int null,
    
    text varchar(400) not null,
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status BOOLEAN DEFAULT TRUE,
    edited BOOLEAN DEFAULT FALSE,

    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (post_id) REFERENCES post(id),
    FOREIGN KEY (parent_comment_id) REFERENCES comments(id) ON DELETE CASCADE
);

--Habilitando cascade delete nas chaves estrangeiras
ALTER TABLE post
DROP CONSTRAINT post_user_id_fkey,
ADD CONSTRAINT post_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE likes
DROP CONSTRAINT likes_user_id_fkey,
ADD CONSTRAINT likes_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE likes
DROP CONSTRAINT likes_post_id_fkey,
ADD CONSTRAINT likes_post_id_fkey FOREIGN KEY (post_id) REFERENCES post(id) ON DELETE CASCADE;

ALTER TABLE comments
DROP CONSTRAINT comments_user_id_fkey,
ADD CONSTRAINT comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE comments
DROP CONSTRAINT comments_post_id_fkey,
ADD CONSTRAINT comments_post_id_fkey FOREIGN KEY (post_id) REFERENCES post(id) ON DELETE CASCADE;

insert into users(name, phone, cpf, email, password, avatar, type)
values(
    'Matheus',
    '988257303',
    '53826433858',
    'math@gmail.com',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZW5oYSI6IjA1MDU4MkBDcmlzIiwiaWF0IjoxNjk0Nzg3Mzg3LCJleHAiOjE2OTQ3OTA5ODd9.h6gK5O0Fm48dF2eLhJpG4vOqZ0c7hZ9sY2tW_tX8rYg',
    'img_exemplo_usuario_base64',
    'USER'
);

insert into users(name, phone, cpf, email, password, avatar, type)
values(
    'Pedro',
    '11988257303',
    '123456789',
    'pedro@gmail.com',
    '0505@Pedro',
    'img_exemplo_usuario_base64',
    'ADMIN'
);

insert into post(user_id, title, text, ingredients, image, time, likes_count, status)
values(
    1,
    'Strogonoff de Frango',
    'Passo a passo: Lorem ipsum dolor sit amet',
    '1kg de Frango, 450g de arroz, 2 alhos, 2 colheres de sopa de manteiga...',
    'img_exemplo_post_base64',
    '45 mins',
    0,
    true
);

insert into post(user_id, title, text, ingredients, image, time, likes_count, status)
values(
    1,
    'Lasanha de Carne',
    'Passo a passo: Lorem ipsum dolor sit amet',
    '1kg de Carne, 450g de arroz, 2 alhos, 2 colheres de sopa de manteiga...',
    'img_exemplo_post_base64',
    '1h',
    0,
    true
);

insert into post(user_id, title, text, ingredients, image, time, likes_count, status)
values(
    1,
    'Strogonoff de Carne',
    'Passo a passo: Lorem ipsum dolor sit amet',
    '1kg de Carne, 450g de arroz, 2 alhos, 2 colheres de sopa de manteiga...',
    'img_exemplo_post_base64',
    '1h',
    0,
    true
);

insert into post(user_id, title, text, ingredients, image, time, likes_count, status)
values(
    2,
    'Feijoada',
    'Passo a passo: Lorem ipsum dolor sit amet',
    '1kg de Carne de porco, 500g de arroz, 500g de couve...',
    'img_exemplo_post_base64',
    '2h',
    0,
    true
);
